### ISSUE TITLE
Consider rename

### ISSUE THREAD

**Issue by matryer** [stretchr/stretchr-backbone#1]
Should this project be called `sdk-backbone` to follow patterns?

**Comment by mazondo** [comment]
Hmmmm maybe for the sake of keeping the github clean. I guess it's an sdk. I guess I thought of it as using the js sdk but not an sdk in and of itself...

```
Sent from my phone
```

**Comment by tylerstillwater** [comment]
sdk-bridge-backbone?

**Comment by matryer** [comment]
in theory - we could remove the `sdk` prefix since the URL contains `/stretchr`.

E.g.

```
github.com/stretchr/js
github.com/stretchr/backbone
github.com/stretchr/cocoa
github.com/stretchr/go
```

etc.

**Comment by tylerstillwater** [comment]
We have other repos, though, that have nothing to do with stretchr itself. I feel the sdk prefix is good for distinguishing them

**Comment by mazondo** [comment]
I'm with Tyler, mostly bc it's nice to hit the "s" part of the list and see all of them

```
Sent from my phone
```

**Comment by tylerstillwater** [comment]
You can also filter by "sdk" and see them all
